name: build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read

    steps:
      # Seed the build number with last number from TeamCity.
      # This env var is used by the JS, and SBT builds, and guardian/actions-riff-raff.
      # Set the value early, rather than `buildNumberOffset` in guardian/actions-riff-raff, to ensure each usage has the same number.
      # For some reason, it's not possible to mutate GITHUB_RUN_NUMBER, so set BUILD_NUMBER instead.
      - name: Set BUILD_NUMBER environment variable
        run: |
          LAST_TEAMCITY_BUILD=145
          echo "BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))" >> $GITHUB_ENV
      - uses: actions/checkout@v4

      # See https://github.com/guardian/setup-java
      - name: Setup Java and sbt
        uses: guardian/setup-scala@v1

      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Build and Test project
        run: |
          sbt clean compile test Universal/packageBin
          cp target/universal/snapshotter-lambda.zip ./snapshotter-lambda.zip

      - uses: guardian/actions-riff-raff@v2
        with:
          projectName: editorial-tools:flexible:snapshotter-lambda
          buildNumber: ${{ env.BUILD_NUMBER }}
          configPath: riff-raff.yaml
          contentDirectories: |
            snapshotter-lambda:
              - snapshotter-lambda.zip